import { INotification, ITopCategory, ITopCollection } from "./interfaces";

export const singleTopCollection: ITopCollection = {
  collectionAlt: "Swanky Stripes",
  collectionName: "Swanky Stripes",
  collectionNumber: "#008",
  collectionSrc: "/collections/collection_1.jfif",
  currentBid: "4.25",
  endingIn: "15h 32m",
  ownerAlt: "Laura W. Norris",
  ownerName: "Laura W. Norris",
  ownerSrc: "/profiles/profile_1.jpg",
  username: "@kettleaching",
};

export const topCollections: ITopCollection[] = [
  {
    collectionAlt: "CryptoPunk",
    collectionName: "CryptoPunk",
    collectionNumber: "#7808",
    collectionSrc: "/collections/collection_1.jfif",
    currentBid: "3.27",
    endingIn: "01h 19m",
    ownerAlt: "Laura W. Norris",
    ownerName: "Laura W. Norris",
    ownerSrc: "/profiles/profile_1.jpg",
    username: "@artscorpion",
  },
  {
    collectionAlt: "Opening Night",
    collectionName: "Opening Night",
    collectionNumber: "#498",
    collectionSrc: "/collections/collection_2.jfif",
    currentBid: "3.32",
    endingIn: "25h 36m",
    ownerAlt: "Ryan K. Shrum",
    ownerName: "Ryan K. Shrum",
    ownerSrc: "/profiles/profile_2.jpg",
    username: "@peacefuldelay",
  },
  {
    collectionAlt: "The Moon Boi",
    collectionName: "The Moon Boi",
    collectionNumber: "#2065",
    collectionSrc: "/collections/collection_3.jfif",
    currentBid: "3.09",
    endingIn: "11h 11m",
    ownerAlt: "Desmond R. Dick",
    ownerName: "Desmond R. Dick",
    ownerSrc: "/profiles/profile_3.jpg",
    username: "@blazerodartichokes",
  },
  {
    collectionAlt: "Diamong Joint",
    collectionName: "Diamong Joint",
    collectionNumber: "#8766",
    collectionSrc: "/collections/collection_4.jfif",
    currentBid: "2.59",
    endingIn: "05h 03m",
    ownerAlt: "Dovie M. Herbert",
    ownerName: "Dovie M. Herbert",
    ownerSrc: "/profiles/profile_4.jpg",
    username: "@obscenesombrero",
  },
  {
    collectionAlt: "The Space Scout",
    collectionName: "The Space Scout",
    collectionNumber: "#902",
    collectionSrc: "/collections/collection_5.jfif",
    currentBid: "2.47",
    endingIn: "00h 05m",
    ownerAlt: "Stephanie R. Downey",
    ownerName: "Stephanie R. Downey",
    ownerSrc: "/profiles/profile_5.jpg",
    username: "@gingerdeserve",
  },
  {
    collectionAlt: "Pablo Etherbar",
    collectionName: "Pablo Etherbar",
    collectionNumber: "#761",
    collectionSrc: "/collections/collection_6.jfif",
    currentBid: "2.45",
    endingIn: "06h 37m",
    ownerAlt: "Freda R. Isom",
    ownerName: "Freda R. Isom",
    ownerSrc: "/profiles/profile_6.jpg",
    username: "@hordebronze",
  },
  {
    collectionAlt: "The Hipster Shib",
    collectionName: "The Hipster Shib",
    collectionNumber: "#111",
    collectionSrc: "/collections/collection_7.jfif",
    currentBid: "4.86",
    endingIn: "03h 08m",
    ownerAlt: "Tressa W. Tatum",
    ownerName: "Tressa W. Tatum",
    ownerSrc: "/profiles/profile_7.jpg",
    username: "@conspiracyprovider",
  },
  {
    collectionAlt: "Daredevil DOGE",
    collectionName: "Daredevil DOGE",
    collectionNumber: "#002",
    collectionSrc: "/collections/collection_8.jfif",
    currentBid: "1.55",
    endingIn: "48h 10m",
    ownerAlt: "Jessica J. Lattimore",
    ownerName: "Jessica J. Lattimore",
    ownerSrc: "/profiles/profile_8.jpg",
    username: "@wearlaboratory",
  },
];

export const topCategories: ITopCategory[] = [
  {
    rank: "1.",
    src: "/profiles/profile_1.jpg",
    alt: "Laura W. Norris",
    name: "Laura W. Norris",
    username: "@kettleaching",
    isFollowing: true,
  },
  {
    rank: "1.",
    src: "/profiles/profile_2.jpg",
    alt: "Ryan K. Shrum",
    name: "Ryan K. Shrum",
    username: "@artscorpion",
    isFollowing: false,
  },
  {
    rank: "1.",
    src: "/profiles/profile_3.jpg",
    alt: "Desmond R. Dick",
    name: "Desmond R. Dick",
    username: "@peacefuldelay",
    isFollowing: false,
  },
  {
    rank: "2.",
    src: "/profiles/profile_4.jpg",
    alt: "Dovie M. Herbert",
    name: "Dovie M. Herbert",
    username: "@blazerodartichokes",
    isFollowing: false,
  },
  {
    rank: "2.",
    src: "/profiles/profile_5.jpg",
    alt: "Stephanie R. Downey",
    name: "Stephanie R. Downey",
    username: "@obscenesombrero",
    isFollowing: true,
  },
  {
    rank: "3.",
    src: "/profiles/profile_6.jpg",
    alt: "Freda R. Isom",
    name: "Freda R. Isom",
    username: "@gingerdeserve",
    isFollowing: true,
  },
  {
    rank: "4.",
    src: "/profiles/profile_7.jpg",
    alt: "Tressa W. Tatum",
    name: "Tressa W. Tatum",
    username: "@hordebronze",
    isFollowing: false,
  },
  {
    rank: "5.",
    src: "/profiles/profile_8.jpg",
    alt: "Jessica J. Lattimore",
    name: "Jessica J. Lattimore",
    username: "@conspiracyprovider",
    isFollowing: false,
  },
  {
    rank: "6.",
    src: "/profiles/profile_9.jpg",
    alt: "Jonas M. Godwin",
    name: "Jonas M. Godwin",
    username: "@wearlaboratory",
    isFollowing: true,
  },
  {
    rank: "7.",
    src: "/profiles/profile_10.jpg",
    alt: "Gerald S. Watkins",
    name: "Gerald S. Watkins",
    username: "@embraceleaf",
    isFollowing: false,
  },
];

export const notifications: INotification[] = [
  {
    alt: "CryptoPunk #7804",
    collectionName: "CryptoPunk #7804",
    priceSold: "3.27",
    src: "/profiles/profile_1.jpg",
  },
  {
    alt: "Opening Night",
    collectionName: "Opening Night",
    priceSold: "3.32",
    src: "/profiles/profile_2.jpg",
  },
  {
    alt: "The Moon Boi",
    collectionName: "The Moon Boi",
    priceSold: "3.09",
    src: "/profiles/profile_3.jpg",
  },
  {
    alt: "Diamong Joint",
    collectionName: "Diamong Joint",
    priceSold: "2.59",
    src: "/profiles/profile_4.jpg",
  },
  {
    alt: "The Space Scout",
    collectionName: "The Space Scout",
    priceSold: "3.23",
    src: "/profiles/profile_5.jpg",
  },
  {
    alt: "Pablo Etherbar",
    collectionName: "Pablo Etherbar",
    priceSold: "2.47",
    src: "/profiles/profile_6.jpg",
  },
  {
    alt: "The Hipster Shib",
    collectionName: "The Hipster Shib",
    priceSold: "2.45",
    src: "/profiles/profile_7.jpg",
  },
  {
    alt: "Swanky Stripes",
    collectionName: "Swanky Stripes",
    priceSold: "4.25",
    src: "/profiles/profile_8.jpg",
  },
  {
    alt: "Daredevil DOGE",
    collectionName: "Daredevil DOGE",
    priceSold: "4.86",
    src: "/profiles/profile_9.jpg",
  },
  {
    alt: "VVS Triple Treat",
    collectionName: "VVS Triple Treat",
    priceSold: "1.55",
    src: "/profiles/profile_10.jpg",
  },
];
