import { ITopCategory } from "./interfaces";

export const topCategories: ITopCategory[] = [
    {
      id: 1,
      rank: "1.",
      src: "/profile.jpg",
      alt: "Profile",
      name: "Marwan",
      username: "@msaad19",
      isFollowing: true,
    },
    {
      id: 2,
      rank: "1.",
      src: "/profile.jpg",
      alt: "Profile",
      name: "Marwan",
      username: "@msaad19",
      isFollowing: false,
    },
    {
      id: 3,
      rank: "1.",
      src: "/profile.jpg",
      alt: "Profile",
      name: "Marwan",
      username: "@msaad19",
      isFollowing: true,
    },
    {
      id: 4,
      rank: "1.",
      src: "/profile.jpg",
      alt: "Profile",
      name: "Marwan",
      username: "@msaad19",
      isFollowing: false,
    },
    {
      id: 5,
      rank: "1.",
      src: "/profile.jpg",
      alt: "Profile",
      name: "Marwan",
      username: "@msaad19",
      isFollowing: true,
    },
    {
      id: 6,
      rank: "1.",
      src: "/profile.jpg",
      alt: "Profile",
      name: "Marwan",
      username: "@msaad19",
      isFollowing: false,
    },
    {
      id: 7,
      rank: "1.",
      src: "/profile.jpg",
      alt: "Profile",
      name: "Marwan",
      username: "@msaad19",
      isFollowing: true,
    },
    {
      id: 8,
      rank: "1.",
      src: "/profile.jpg",
      alt: "Profile",
      name: "Marwan",
      username: "@msaad19",
      isFollowing: false,
    },
  ];